#!/bin/bash

#
# Create an operator user for sancho
# Required paramters:
#   - operator user name
#   - operator public SSH key
#

function help {
    echo "$0 <user> <ssh_pub_key_file>"
    exit 1
}

user=$1
key=$2

if [ -z $user ] || [ -z $key ]; then
   help
fi

id $user &>/dev/null

if [ $? -eq 0 ]; then
   echo "$user already exists"
   exit 1
fi


if [ ! -f $key ]; then
    echo "'$key': no such file"
    exit 1
fi

adduser -G ronzinante $user

if [ $? -gt 0 ]; then
    echo "Creation of user '$user' failed"
    exit 1
fi
mkdir -p /home/$user/.ssh
cat $key > /home/$user/.ssh/authorized_keys
chmod 600 /home/$user/.ssh/authorized_keys
chown -R $user:$user /home/$user/.ssh/